import React, {useRef} from 'react';
import Head from "next/head";
import Header from "../Header/Header";
import SideBar from "../SideBar/SideBar";
import styles from './Layout.module.css'
import {useAppSelector} from "../../store/store";
import Alert from "../../common/Alert/Alert";
const Layout:React.FC<{children?:JSX.Element | JSX.Element[] }> = ({children}) => {
    const isSideBarOpen=useAppSelector(state =>state.sideBar.isOpen);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
                <div className={styles.wrapper}>
                    <Header/>
                    <main className={styles.main}>
                        {isSideBarOpen && <SideBar/>}
                        {children}
                    </main>
                    <Alert/>
                </div>
        </>
    );
};
export default Layout;
